[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "mistral-vibe"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
uv = ">=0.11.13,<0.12"
python = "3.13.*"
mistralai = "2.4.4.*"
jsonpatch = ">=1.33,<2"
pexpect = ">=4.9.0,<5"
hatchling = ">=1.29.0,<2"
