[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "mistral-vibe"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
uv = ">=0.9.16,<0.10"
python = "3.13.*"
